-- ============================================================
-- 부하 테스트용 유저 seed
-- 실행 전: BCRYPT_HASH 자리에 실제 해시값을 넣을 것
--
-- BCrypt 해시 생성 방법 (비밀번호: Test1234!, rounds=10):
--   $ htpasswd -bnBC 10 "" Test1234! | tr -d ':\n'
-- ============================================================

SET @password_hash = '$2a$12$NZxQIubFeVpXYzCiruohjuzFZjA.UyGVeLtndK.KGpvDO.g6A3BcS';
SET @now = NOW(6);

-- 호스트 계정 (이벤트 생성용)
INSERT IGNORE INTO users (email, name, password_hash, created_at, updated_at)
VALUES ('loadtest-host@example.com', 'LoadTest Host', @password_hash, @now, @now);

-- 참여자 계정 100명 (loadtest-user-0 ~ loadtest-user-99)
INSERT IGNORE INTO users (email, name, password_hash, created_at, updated_at) VALUES
('loadtest-user-0@example.com',  'LoadTest User 0',  @password_hash, @now, @now),
('loadtest-user-1@example.com',  'LoadTest User 1',  @password_hash, @now, @now),
('loadtest-user-2@example.com',  'LoadTest User 2',  @password_hash, @now, @now),
('loadtest-user-3@example.com',  'LoadTest User 3',  @password_hash, @now, @now),
('loadtest-user-4@example.com',  'LoadTest User 4',  @password_hash, @now, @now),
('loadtest-user-5@example.com',  'LoadTest User 5',  @password_hash, @now, @now),
('loadtest-user-6@example.com',  'LoadTest User 6',  @password_hash, @now, @now),
('loadtest-user-7@example.com',  'LoadTest User 7',  @password_hash, @now, @now),
('loadtest-user-8@example.com',  'LoadTest User 8',  @password_hash, @now, @now),
('loadtest-user-9@example.com',  'LoadTest User 9',  @password_hash, @now, @now),
('loadtest-user-10@example.com', 'LoadTest User 10', @password_hash, @now, @now),
('loadtest-user-11@example.com', 'LoadTest User 11', @password_hash, @now, @now),
('loadtest-user-12@example.com', 'LoadTest User 12', @password_hash, @now, @now),
('loadtest-user-13@example.com', 'LoadTest User 13', @password_hash, @now, @now),
('loadtest-user-14@example.com', 'LoadTest User 14', @password_hash, @now, @now),
('loadtest-user-15@example.com', 'LoadTest User 15', @password_hash, @now, @now),
('loadtest-user-16@example.com', 'LoadTest User 16', @password_hash, @now, @now),
('loadtest-user-17@example.com', 'LoadTest User 17', @password_hash, @now, @now),
('loadtest-user-18@example.com', 'LoadTest User 18', @password_hash, @now, @now),
('loadtest-user-19@example.com', 'LoadTest User 19', @password_hash, @now, @now),
('loadtest-user-20@example.com', 'LoadTest User 20', @password_hash, @now, @now),
('loadtest-user-21@example.com', 'LoadTest User 21', @password_hash, @now, @now),
('loadtest-user-22@example.com', 'LoadTest User 22', @password_hash, @now, @now),
('loadtest-user-23@example.com', 'LoadTest User 23', @password_hash, @now, @now),
('loadtest-user-24@example.com', 'LoadTest User 24', @password_hash, @now, @now),
('loadtest-user-25@example.com', 'LoadTest User 25', @password_hash, @now, @now),
('loadtest-user-26@example.com', 'LoadTest User 26', @password_hash, @now, @now),
('loadtest-user-27@example.com', 'LoadTest User 27', @password_hash, @now, @now),
('loadtest-user-28@example.com', 'LoadTest User 28', @password_hash, @now, @now),
('loadtest-user-29@example.com', 'LoadTest User 29', @password_hash, @now, @now),
('loadtest-user-30@example.com', 'LoadTest User 30', @password_hash, @now, @now),
('loadtest-user-31@example.com', 'LoadTest User 31', @password_hash, @now, @now),
('loadtest-user-32@example.com', 'LoadTest User 32', @password_hash, @now, @now),
('loadtest-user-33@example.com', 'LoadTest User 33', @password_hash, @now, @now),
('loadtest-user-34@example.com', 'LoadTest User 34', @password_hash, @now, @now),
('loadtest-user-35@example.com', 'LoadTest User 35', @password_hash, @now, @now),
('loadtest-user-36@example.com', 'LoadTest User 36', @password_hash, @now, @now),
('loadtest-user-37@example.com', 'LoadTest User 37', @password_hash, @now, @now),
('loadtest-user-38@example.com', 'LoadTest User 38', @password_hash, @now, @now),
('loadtest-user-39@example.com', 'LoadTest User 39', @password_hash, @now, @now),
('loadtest-user-40@example.com', 'LoadTest User 40', @password_hash, @now, @now),
('loadtest-user-41@example.com', 'LoadTest User 41', @password_hash, @now, @now),
('loadtest-user-42@example.com', 'LoadTest User 42', @password_hash, @now, @now),
('loadtest-user-43@example.com', 'LoadTest User 43', @password_hash, @now, @now),
('loadtest-user-44@example.com', 'LoadTest User 44', @password_hash, @now, @now),
('loadtest-user-45@example.com', 'LoadTest User 45', @password_hash, @now, @now),
('loadtest-user-46@example.com', 'LoadTest User 46', @password_hash, @now, @now),
('loadtest-user-47@example.com', 'LoadTest User 47', @password_hash, @now, @now),
('loadtest-user-48@example.com', 'LoadTest User 48', @password_hash, @now, @now),
('loadtest-user-49@example.com', 'LoadTest User 49', @password_hash, @now, @now),
('loadtest-user-50@example.com', 'LoadTest User 50', @password_hash, @now, @now),
('loadtest-user-51@example.com', 'LoadTest User 51', @password_hash, @now, @now),
('loadtest-user-52@example.com', 'LoadTest User 52', @password_hash, @now, @now),
('loadtest-user-53@example.com', 'LoadTest User 53', @password_hash, @now, @now),
('loadtest-user-54@example.com', 'LoadTest User 54', @password_hash, @now, @now),
('loadtest-user-55@example.com', 'LoadTest User 55', @password_hash, @now, @now),
('loadtest-user-56@example.com', 'LoadTest User 56', @password_hash, @now, @now),
('loadtest-user-57@example.com', 'LoadTest User 57', @password_hash, @now, @now),
('loadtest-user-58@example.com', 'LoadTest User 58', @password_hash, @now, @now),
('loadtest-user-59@example.com', 'LoadTest User 59', @password_hash, @now, @now),
('loadtest-user-60@example.com', 'LoadTest User 60', @password_hash, @now, @now),
('loadtest-user-61@example.com', 'LoadTest User 61', @password_hash, @now, @now),
('loadtest-user-62@example.com', 'LoadTest User 62', @password_hash, @now, @now),
('loadtest-user-63@example.com', 'LoadTest User 63', @password_hash, @now, @now),
('loadtest-user-64@example.com', 'LoadTest User 64', @password_hash, @now, @now),
('loadtest-user-65@example.com', 'LoadTest User 65', @password_hash, @now, @now),
('loadtest-user-66@example.com', 'LoadTest User 66', @password_hash, @now, @now),
('loadtest-user-67@example.com', 'LoadTest User 67', @password_hash, @now, @now),
('loadtest-user-68@example.com', 'LoadTest User 68', @password_hash, @now, @now),
('loadtest-user-69@example.com', 'LoadTest User 69', @password_hash, @now, @now),
('loadtest-user-70@example.com', 'LoadTest User 70', @password_hash, @now, @now),
('loadtest-user-71@example.com', 'LoadTest User 71', @password_hash, @now, @now),
('loadtest-user-72@example.com', 'LoadTest User 72', @password_hash, @now, @now),
('loadtest-user-73@example.com', 'LoadTest User 73', @password_hash, @now, @now),
('loadtest-user-74@example.com', 'LoadTest User 74', @password_hash, @now, @now),
('loadtest-user-75@example.com', 'LoadTest User 75', @password_hash, @now, @now),
('loadtest-user-76@example.com', 'LoadTest User 76', @password_hash, @now, @now),
('loadtest-user-77@example.com', 'LoadTest User 77', @password_hash, @now, @now),
('loadtest-user-78@example.com', 'LoadTest User 78', @password_hash, @now, @now),
('loadtest-user-79@example.com', 'LoadTest User 79', @password_hash, @now, @now),
('loadtest-user-80@example.com', 'LoadTest User 80', @password_hash, @now, @now),
('loadtest-user-81@example.com', 'LoadTest User 81', @password_hash, @now, @now),
('loadtest-user-82@example.com', 'LoadTest User 82', @password_hash, @now, @now),
('loadtest-user-83@example.com', 'LoadTest User 83', @password_hash, @now, @now),
('loadtest-user-84@example.com', 'LoadTest User 84', @password_hash, @now, @now),
('loadtest-user-85@example.com', 'LoadTest User 85', @password_hash, @now, @now),
('loadtest-user-86@example.com', 'LoadTest User 86', @password_hash, @now, @now),
('loadtest-user-87@example.com', 'LoadTest User 87', @password_hash, @now, @now),
('loadtest-user-88@example.com', 'LoadTest User 88', @password_hash, @now, @now),
('loadtest-user-89@example.com', 'LoadTest User 89', @password_hash, @now, @now),
('loadtest-user-90@example.com', 'LoadTest User 90', @password_hash, @now, @now),
('loadtest-user-91@example.com', 'LoadTest User 91', @password_hash, @now, @now),
('loadtest-user-92@example.com', 'LoadTest User 92', @password_hash, @now, @now),
('loadtest-user-93@example.com', 'LoadTest User 93', @password_hash, @now, @now),
('loadtest-user-94@example.com', 'LoadTest User 94', @password_hash, @now, @now),
('loadtest-user-95@example.com', 'LoadTest User 95', @password_hash, @now, @now),
('loadtest-user-96@example.com', 'LoadTest User 96', @password_hash, @now, @now),
('loadtest-user-97@example.com', 'LoadTest User 97', @password_hash, @now, @now),
('loadtest-user-98@example.com', 'LoadTest User 98', @password_hash, @now, @now),
('loadtest-user-99@example.com', 'LoadTest User 99', @password_hash, @now, @now);
